<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BenchmarkWorkloads\BenchmarkWorkloads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Kralizek.Lambda.Template" Version="5.0.0" />
  </ItemGroup>

</Project>
