<Project>
  <PropertyGroup>
    <RootNamespace>Kralizek.Lambda</RootNamespace>
    <Authors>Renato Golia</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Kralizek/AWSLambdaSharpTemplate</PackageProjectUrl>
    <NoWarn>NU5105,NU5125</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
