<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.AWS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventFunction\EventFunction.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\RequestFunction\RequestFunction.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\SqsFunction\SqsFunction.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
