<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Kralizek.Lambda.Template.KinesisStreams</PackageId>
    <PackageTags>aws-lambda-csharp;dotnet-core;aws-lambda;aws;lambda;csharp;kinesis;streams</PackageTags>
    <Description>Extension to Kralizek.Lambda.Template for AWS Lambda functions triggered by Amazon Kinesis Data Streams.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kralizek.Lambda.Template\Kralizek.Lambda.Template.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.KinesisEvents" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>