<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tests.Lambda</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.TestUtilities" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="GitHubActionsTestLogger" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template\Kralizek.Lambda.Template.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.Cognito\Kralizek.Lambda.Template.Cognito.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.DynamoDbStreams\Kralizek.Lambda.Template.DynamoDbStreams.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.EventBridge\Kralizek.Lambda.Template.EventBridge.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.KinesisStreams\Kralizek.Lambda.Template.KinesisStreams.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.S3\Kralizek.Lambda.Template.S3.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.Sns\Kralizek.Lambda.Template.Sns.csproj" />
    <ProjectReference Include="..\..\src\Kralizek.Lambda.Template.Sqs\Kralizek.Lambda.Template.Sqs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CustomSerializerTests.cs" />
  </ItemGroup>

</Project>
