name: Benchmark history

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      publish_history:
        description: Publish results to benchmark history
        type: boolean
        required: false
        default: false

concurrency:
  group: benchmark-history-${{ github.ref }}
  cancel-in-progress: false

jobs:
  benchmark:
    name: Run benchmarks
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/release-benchmarks.yml
    with:
      publish-history: ${{ github.event_name == 'push' || inputs.publish_history }}
      release-mode: false
